### ISSUE TITLE
Affichage des résultats de l'analyse d'un fichier BAL trop volumineux impossible 

### ISSUE THREAD

**Issue by tmerlier** [etalab/adresse.data.gouv.fr#100]
Lors de l'analyse d'un fichier BAL trop volumineux, l'interface devient trop gourmande en ressource et fait planter le navigateur.

De plus l'affichage l'affichage ligne par ligne ne semble pas être pertinent en vu de la quantité important d'information contenu dans ce type de fichier.

**Comment by jdesboeufs** [comment]
Pour l'analyse : `WebWorker` + informations sur la progression
Pour l'affichage en effet il va falloir réfléchir un peu.

**Comment by tmerlier** [comment]
L'affichage n'est plus un problème depuis #200
