### ISSUE TITLE
Le marqueur ne positionne pas le lieu par la pointe

### ISSUE THREAD

**Issue by vinyll** [etalab/adresse.data.gouv.fr#103]
Le marqueur bleu devrait positionner une localisation par sa pointe, or il semble être positionné par son rond blanc ou sa partie supérieure par un décalage vertical.
Une image vaut mieux qu'on long discours…

La maison se trouve en bord de rue au niveau supérieur du marqueur (ici il est encore un peu bas, mais montre à peu près la localisation) :
<img width="404" alt="screen shot 2018-02-19 at 8 39 19 am" src="https://user-images.githubusercontent.com/145172/36383393-9d4671e6-1551-11e8-9938-d1b03cb95acc.png">

En vue dézoomée, le décalage vertical est plus flagrant :
<img width="392" alt="screen shot 2018-02-19 at 8 38 58 am" src="https://user-images.githubusercontent.com/145172/36383477-dc80e58a-1551-11e8-86b9-77e92e532228.png">

**Comment by tusbar** [comment]
@vinyll Merci, c'est réglé !

**Comment by jdesboeufs** [comment]
Et déployé ;)
