### ISSUE TITLE
Format du champ unique de l'adresse à géocoder

### ISSUE THREAD

**Issue by kqueekquee** [etalab/adresse.data.gouv.fr#116]
Géocodage selon un seul champ formaté avec l'adresse . Sous quelle forme doit être ce champ ? 
N°+rue+CP+Commune+INSEE ? faut il un séparateur entre chaque élément de la chaine ?

ici un exemple d'une adresse mal géocodée

![25056](https://user-images.githubusercontent.com/921519/38780263-f502712a-40d3-11e8-8ff1-2c7fc2aca29e.jpg)

[TEST_geocoded.zip](https://github.com/etalab/adresse.data.gouv.fr/files/1913017/TEST_geocoded.zip)

**Comment by jdesboeufs** [comment]
Vous devez utilisez le paramètre `columns`, à passer en multipart. Il faut répéter ce paramètre autant de fois que nécessaire, dans l’ordre de composition de l’adresse.
