### ISSUE TITLE
Incompatibilité avec de nombreux navigateurs

### ISSUE THREAD

**Issue by tmerlier** [etalab/adresse.data.gouv.fr#124]
https://www.browserstack.com/screenshots/08f1fff6d602e9aefa4800405d74327579b9887b

**Comment by jdesboeufs** [comment]
Actuellement l'affichage des pages nécessitant WebGL sur des navigateurs ne le supportant pas fait planter le site avec une "erreur 500".

Il faudrait a minima détecter la présence de WebGL et faire ce qu'il faut : avertir, proposer du contenu de remplacement…

**Comment by jdesboeufs** [comment]
https://github.com/etalab/geo.data.gouv.fr/issues/627

**Comment by jdesboeufs** [comment]
T’as vérifié que les bugs ci-dessus sont corrigés avant de fermer ?

**Comment by tmerlier** [comment]
Oui. Il reste quelques problèmes mineur de CSS qu'il faudra revérifier et arranger.
