### ISSUE TITLE
Possibilité d'obtenir circonscription législative par l'adresse ?

### ISSUE THREAD

**Issue by udewilde** [etalab/adresse.data.gouv.fr#130]
Bonjour, 
serait-il possible d'obtenir le code de la circonscription électorale d'une adresse donnée (sous forme d'adresse ou de geocode) ?

Je ne parviens pas à trouver cette information dans la response.
Idéalement, recevoir une réponse comme sur le site de [Le Parisien](http://www.leparisien.fr/elections/legislatives/legislatives-quelle-est-votre-circonscription-electorale-16-05-2017-6953487.php) 

Merci

**Comment by jdesboeufs** [comment]
Bonjour,

Il suffit de croiser les résultats de l'API de géocodage avec un jeu de données des contours des circonscriptions de la période considérée.
Par exemple celui-ci : https://www.data.gouv.fr/fr/datasets/contours-precis-des-circonscriptions-legislatives/
