### ISSUE TITLE
[BAL] Comparer une BAL avec la BAN / BANO / Cadastre

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/adresse.data.gouv.fr#148]
Mettre en place un outil simple permettant de comparer une BAL avec les données présentes dans la BAN (ou la BANO, ou le Cadastre).

Cet outil doit paver la route vers une synchronisation avec la BAN (développement ultérieur).

**Comment by biratchet** [comment]
Ce serait tellement bien ;)

**Comment by jdesboeufs** [comment]
On a déjà une interface cachée pour comparer BAN, BANO et Cadastre 😄

**Comment by jdesboeufs** [comment]
Largement obsolète ;)
