### ISSUE TITLE
Geocoder CSV pas de résultat blocage proxy ou firewall

### ISSUE THREAD

**Issue by jpklipfel** [etalab/adresse.data.gouv.fr#15]
Le geocoder CSV ne fonctionne pas chez moi (testé sous FF, Chrome ou IE)
Aucun résultat, cela tourne indéfiniment

**Comment by yohanboniface** [comment]
Quelle taille du fichier CSV? Quel encodage? Est-ce que ça bug avec tous les fichiers CSV testés?

**Comment by jpklipfel** [comment]
C'était un juste un test avec quelques lignes:

````
680010010K-11	11	Rue des Alpes	68600	Algolsheim	OSM	48.001935	7.556450
680010010K-1	1	Rue des Alpes	68600	Algolsheim	OSM	48.002987	7.556451
680010010K-12	12	Rue des Alpes	68600	Algolsheim	OSM	48.001767	7.556117
680010010K-13	13	Rue des Alpes	68600	Algolsheim	OSM	48.001769	7.556468
680010010K-14	14	Rue des Alpes	68600	Algolsheim	OSM	48.001525	7.556143
680010010K-15	15	Rue des Alpes	68600	Algolsheim	OSM	48.001553	7.556523
680010010K-16	16	Rue des Alpes	68600	Algolsheim	OSM	48.001334	7.556036
680010010K-18	18	Rue des Alpes	68600	Algolsheim	OSM	48.001319	7.556313
680010010K-20	20	Rue des Alpes	68600	Algolsheim	OSM	48.001319	7.556641
680010010K-22	22	Rue des Alpes	68600	Algolsheim	OSM	48.001313	7.556937

**Comment by yohanboniface** [comment]
Ah, sans headers?

**Comment by jpklipfel** [comment]
Testé sans succès avec headers (je sélectionne les colonnes NUM, VOIE, INSEE, COMMUNE pour le géocodage)

**Comment by yohanboniface** [comment]
Tu peux m'envoyer le fichier brut de pomme à yohan.boniface@data.gouv.fr?

**Comment by yohanboniface** [comment]
Humm, merci. Chez moi ça passe sans aucun souci.
OS? Version de FF?

**Comment by jpklipfel** [comment]
Windows 7 pro / FF 36

**Comment by yohanboniface** [comment]
humm, je viens de tester sur le seul Windows que j'aie à portée de main (mais FF 24, pas de possibilité de mettre à jour ni d'installer Chrome) et je ne reproduis pas :/

Est-ce que tu peux regarder s'il y a un message dans la console? (Ctrl-Shift-K sur Firefox, l'ouvrir avant d'appuyer sur envoyer)

**Comment by jpklipfel** [comment]
URL de la requête : 	http://api-adresse.data.gouv.fr/csv/
Méthode de la requête : 	OPTIONS
Code d'état : 	HTTP/1.0 403 Forbidden
En-têtes de la requête 16:16:27,000
User-Agent:	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0
Pragma:	no-cache
Origin:	http://adresse.data.gouv.fr
Host:	api-adresse.data.gouv.fr
Connection:	keep-alive
Cache-Control:	no-cache
Access-Control-Request-Method:	POST
Accept-Language:	fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding:	gzip, deflate
Accept:	text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
En-têtes de la réponse Δ4ms
X-Squid-Error:	ERR_ACCESS_DENIED 0
X-Cache-Lookup:	NONE from localhost:3127
X-Cache:	MISS from localhost
Via:	1.0 localhost (squid/3.1.19)
Vary:	Accept-Language
Server:	squid/3.1.19

**Comment by yohanboniface** [comment]
Hummm, je me demande bien ce que Squid vient faire là, ça sent le proxy local. Tu aurais moyen de tester depuis une autre ligne Internet (genre partage 3G)?

**Comment by jpklipfel** [comment]
Testé sur le wifi sans proxy mais derrière un FireWall

Toujours Squid error, j'essaierai chez moi

**Comment by yohanboniface** [comment]
ok merci :)

**Comment by jpklipfel** [comment]
Testé à la maison : ça marche très bien
... mais les conditions ne sont pas les mêmes (OS linux, pas de proxy ...)

Ticket à fermer?

**Comment by yohanboniface** [comment]
Non, pas forcément à fermer, il peut y avoir une merdouille côté headers chez nous. Ça va pas être évident à pister, mais je préfère laisser ouvert pour garder en tête.

D'autant que, même si c'est pas un souci côté addok, ce serait bien que ça marche même pour ceux qui sont derrière un proxy un peu agressif.

Bref, je vais faire une passe de contrôle sur les headers qu'on renvoie.

**Comment by jdbouvier** [comment]
Même problème rencontré pour moi, un fichier CSV minimaliste ne passe pas, quelque soit le navigateur. En regardant dans la console, je retrouve squid/3.1.19

**Comment by thibdrev** [comment]
Erreur également ici. Ubuntu 14.04, firefox 40.0.3

J'ai essayé de re-géocoder le fichier un fichier de l'Éducation Nationale, disponible ici :
https://www.data.gouv.fr/s/resources/adresse-et-geolocalisation-des-etablissements-denseignement-du-premier-et-second-degres/community/20150116-105239/depp-etablissements-premier-et-second-degres-structures-administratives-education-avril-2014.txt
Le fichier fait 12.7Mo. Tout se passe bien mais arrivé à ~95% la barre ne progresse plus et Addok finit par afficher un message d'erreur.

J'ai réessayé avec le même fichier mais en gardant uniquement les colonnes intéressante (3.2Mo, en csv ce coup-ci). Ça progresse plus vite mais bloque toujours à la fin.

**Comment by thibdrev** [comment]
Même mesage d'erreur un peu plus tard, depuis la même connexion mais avec un Mac 10.10.5 et Safari 8.0.8 : Oops, quelque chose tourne pas rond…

**Comment by thibdrev** [comment]
Même message d'erreur ce matin avec le même fichier depuis un réseau d'entreprise (Win7Pro, Firefox 40.0.3).
Par contre en ne prenant que les lignes du département du Cher, cela réduit le fichier à 19KB et là ça passe. Le fichier renvoyé par addok fait alors 82KB (x4).
Y a-t-il une limite de taille ou de lignes pour les fichiers en entrée?

**Comment by laurenthembord** [comment]
Soucis avec le fichier BAN_licence_gratuite_repartage_56 (je n'ai pas testé avec les autres fichiers).
Les fichiers sont enregistrés tels quels sur le pc avec OpenOffice.
Windows 10 sous Chrome 47.0.2526.80 m : à jour.
La barre de défilement progresse jusque 5, puis redémarre pour redéfiler jusque 5 (carreaux);
et là, oups.....
Dans la console j'ai ça : 
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
http://api-adresse.data.gouv.fr/search/csv/ Failed to load resource: net::ERR_CONNECTION_RESET.

**Comment by cquest** [comment]
Issue orpheline et plus d'actualité...
