### ISSUE TITLE
[BAL] Zoom trop important lorsqu'il y a peu de points

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/adresse.data.gouv.fr#154]
Lorsqu'on affiche les adresses d'une voie avec quelque numéros, ou la position d'un toponyme, le niveau de zoom par défaut est trop important pour que la carte apporte une information utile.

Il faudrait un zoom maximum pour la preview, mais laisser l'utilisateur zoomer plus si ça le chante.

Exemple pour un rond-point :

<img width="1020" alt="capture d ecran 2018-07-09 a 16 18 53" src="https://user-images.githubusercontent.com/1231232/42455897-ca98f0a0-8393-11e8-8aff-d17a864ad4f4.png">

Ceci me parait plus adapté :

<img width="1018" alt="capture d ecran 2018-07-09 a 16 19 46" src="https://user-images.githubusercontent.com/1231232/42455967-f436b29e-8393-11e8-953e-cab66fc3627e.png">

**Comment by tmerlier** [comment]
Corrigé par #155 Ajout d'un zoom maximum pour l'affichage initial
