### ISSUE TITLE
corrections landing page BAL

### ISSUE THREAD

**Issue by Ariane-Rose** [etalab/adresse.data.gouv.fr#1545]
- Améliore**z** (titre)
- Base**s** Adresse**s** Locale**s** est un programme **de l'ANCT** (sous titre)
- Sans frais et sans compétence technique (sous le bouyton "simple" à droite)
- Le programme Base**s** Adresse**s** Locale**s** permet ... (phrase au dessus des logos)
- **Faites** l'état des lieux (action 1)
- Repére**z** les adresses (action 1)
- Crée**z** une base pour **votre** commune (action 1)
- Harmonise**z** vos adresses (action 2)
- et délib**é**rez (action 2)
- **Découvrez** les bonnes pratiques (action 2)
- peut on mettre à jour le chiffre automatiquement ? 12 667 est déjà périmé
- ne plus a**voir**_Consulter_ à y revenir.  (dans le témoignage du maire de Kerfourn à droite on a un mot en trop au milieu)
- Joël Marivain**,** maire de Kerfourn (virgule manquante)

**Comment by MaGOs92** [comment]
Done!
