### ISSUE TITLE
Geocodage inverse : resultat vide

### ISSUE THREAD

**Issue by jbdesbas** [etalab/adresse.data.gouv.fr#164]
Bonjour,

L'API de geocodage inverse retourne un résultat vide lorsque l'adresse n'est pas trouvée (ex : https://api-adresse.data.gouv.fr/reverse/?lon=2.922938069157283&lat=44.78533638665951)
Ne devrait t'elle pas retourner au minimum le code Insee de la commune ? 

❓

**Comment by jdesboeufs** [comment]
Bonjour.

Il s'agit d'une API orientée Adresse.
Si vous voulez compléter votre géocodage inverse, je vous suggère d'utiliser en plus l'API Géo.

Avec votre exemple : https://geo.api.gouv.fr/communes?lon=2.922938069157283&lat=44.78533638665951

La documentation : https://geo.api.gouv.fr
