### ISSUE TITLE
Test du validateur BAL

### ISSUE THREAD

**Issue by mkazmiers** [etalab/adresse.data.gouv.fr#165]
Bonjour,

Est-ce que le validateur BAL est fonctionnel ?

Nous avons reçu sur datasud un fichier BAL affiché comme conforme au SCDL et donc au format AITF SIG TOPO, passé en utf8 pour le test : https://trouver.datasud.fr/dataset/413f3916-a2ea-473b-bd66-dc280ada961e/resource/b2a55c3e-c878-4a06-ab49-a441a67fb949/download/antibes_dir_base_adresses_locales_vd.csv

On vous fait quelques retours. 

1. on a pas réussi à faire fonctionner le validateur en rentrant l'URL. Par contre, par upload de fichiers ça fonctionne très bien.

2. Le validateur détecte des anomalies : 
![image](https://user-images.githubusercontent.com/16324693/45871280-5d68fc80-bd8d-11e8-823f-d59777661b98.png)
Le contenu des lignes ne s'affichent pas. Pas forcément très facile pour l'utilisateur final d'imaginer ce qu'il est en train de regarder. Par contre, le retour vers les champs manquants est OK et clair.

3. Ensuite, en fin de rapport, on affiche les champs obligatoires et les champs non reconnus. on constate que certains sont bel et bien présents mais avec une casse différente.
![image](https://user-images.githubusercontent.com/16324693/45871570-14657800-bd8e-11e8-963a-72f7a083d900.png)

On se disait aussi que ce serait bien de pouvoir avoir un export PDF ou autre du résultat du rapport, c'est souvent plus simple à manipuler pour les agents.

Voilà !

(ai essayé aussi sur dev.validata.fr, le fichier est trop volumineux pour ce validatuer pour l'instant)

**Comment by jdesboeufs** [comment]
Hello.
Oui je confirme que pour le moment le validateur est sensible à la casse sur les champs.
C'est quelque chose qu'on pourrait faire évoluer, mais je ne suis pas sûr que ce soit très pertinent.
Il faudrait vraiment que le producteur en question ait des problématiques techniques légitimes.

On va regarder pour corriger les deux bugs que vous pointez : contenu vide et validation par URL.

Pour le PDF, ce n'est pas prévu, nos ressources sont limités, et ce genre de fonctionnalités est coûteux à mettre en place pour un usage limité.

**Comment by jdesboeufs** [comment]
Lorsque les colonnes ne sont pas connues du modèle, le rendu ne les affiche pas correctement.
Je propose de les afficher mais de mettre une couleur grise sur la colonne en question.
