### ISSUE TITLE
Error Mapbox GL à l'affichage des cartes

### ISSUE THREAD

**Issue by tmerlier** [etalab/adresse.data.gouv.fr#167]
Ces deux erreurs ne gênent pas le bon fonctionnement du programme mais s'affichent en console à chaque fois qu'une carte charge.

![capture d ecran 2018-09-25 a 10 26 30](https://user-images.githubusercontent.com/7040549/46002360-2c027080-c0ae-11e8-8099-01f3fabd9f16.png)

**Comment by jdesboeufs** [comment]
C'est aussi le cas sur les autres cartes du site ?

**Comment by tmerlier** [comment]
Oui.

**Comment by tmerlier** [comment]
Cette erreur est provoquée par le bloqueur de publicités.
