### ISSUE TITLE
Paramètre limit=1 dans API geocodeur : tri par score ?

### ISSUE THREAD

**Issue by bmalan** [etalab/adresse.data.gouv.fr#18]
@yohanboniface 
Bonjour

#### limit=**1**

Dans cet url de l'api (nom d'une ville, ex : *Gebwiller*) : 
http://api-adresse.data.gouv.fr/search/?q=gebwiller&limit=1

L'unique objet JSON envoyé est (tronqué à name, score, postcode, city, type) : 
`"name": "Rue J\u00e9rome Gebwiller", "id": "681620460Z", "score": 0.6580454545454545, "postcode": "68240", "city": "**Kaysersberg**", "type": "street"`

...alors que le résultat le plus pertinent serait plutôt la ville de Gebwiller, et non pas la rue Jérome Gebwiller à Kaysersberg.

#### limit=**2**

Cette fois, je rentre limit = 2 : 
http://api-adresse.data.gouv.fr/search/?q=gebwiller&limit=2

L'unique objet JSON envoyé est (toute la réponse) : 
`{"attribution": "BANO", "licence": "ODbL", "query": "gebwiller", "type": "FeatureCollection", "version": "draft", "features": [{"properties": {"context": "68, Haut-Rhin, Alsace", "label": "Guebwiller", "name": "Guebwiller", "id": "68112", "score": 0.6842818181818181, "postcode": "68500", "city": "Guebwiller", "type": "city"}, "geometry": {"type": "Point", "coordinates": [7.21026, 47.907239]}, "type": "Feature"}, {"properties": {"context": "68, Haut-Rhin, Alsace", "label": "Rue J\u00e9rome Gebwiller 68240 Kaysersberg", "name": "Rue J\u00e9rome Gebwiller", "id": "681620460Z", "score": 0.6580454545454545, "postcode": "68240", "city": "Kaysersberg", "type": "street"}, "geometry": {"type": "Point", "coordinates": [7.259642, 48.13924]}, "type": "Feature"}]}`

Dans l'ordre des objets "trouvés", on retrouve *la ville de Gebwiller* et *la rue Jérome Gebwiller à Kaysersberg*. La *ville* a un meilleur score que la *rue Gebwiller dans Kaysersberg*....

Dans chaque requête de l'API avec **limit > 1**, on retrouve les objets classés par ordre décroissant de **score**. Pourquoi donc, lorsque je mets limit=1, l'unique objet qui ressort n'est pas celui avec le meilleur score ?

Merci

**Comment by bmalan** [comment]
Autre fait étrange : 
lorsque je fais cette requête q=mulhouse : 
http://api-adresse.data.gouv.fr/search/?q=mulhouse&limit=1
le problème n'est plus là!!!
 et c'est bien la ville qui est renvoyée du premier coup (**limit=1**).

Dans le cas **limit=2**, le **score** de la ville est 0.95 et le résultat suivant a un score de 0.69 !

**Comment by yohanboniface** [comment]
Je vois "G**u**ebwiller" pour la ville, avec un "u" donc. Ceci explique pourquoi il est pas dans le premier panier.

**Comment by bmalan** [comment]
Ceci explique cela. ça explique tout même.
merci ...

**Comment by bmalan** [comment]
Vous confirmez que limit=1 grade le meilleur score du panier ?

Merci beaucoup, désolé de mon erreur d'étourderie !

**Comment by yohanboniface** [comment]
> Vous confirmez que limit=1 grade le meilleur score du panier ?

Oui :)

Pour info, les tickets concernant l'API sont plutôt à faire du côté d'[addok](https://github.com/etalab/addok) :)
