### ISSUE TITLE
Information sur le contenu téléchargé

### ISSUE THREAD

**Issue by vdct** [etalab/adresse.data.gouv.fr#19]
À aucun moment dans le processus de téléchargement (formulaire, puis mail reçu) on sait ce qu'on va télécharger. Il faudrait un texte explicatif à une des étapes pour ne pas découvrir en cliquant sur le lien de téléchargement qu'on en prend pour un petit Go de données. L'occasion aussi de préciser le périmètre géo et le format.

**Comment by cquest** [comment]
Fait: https://github.com/etalab/adresse.data.gouv.fr/commit/76ca01379f11f9482ac6448623e67bcc73a5d4fd
