### ISSUE TITLE
Problème d'accès à l'API avec des requettes AJAX (CORS)

### ISSUE THREAD

**Issue by bmarwane** [etalab/adresse.data.gouv.fr#220]
Bonjour,

Il n'est pas possible de faire des requettes depuis Javascript car les requettes preflight sont bloquées par l'API ( voir capture)
![image](https://user-images.githubusercontent.com/1775843/51666954-3468aa80-1fbf-11e9-8f74-3d5d19b501c9.png)

Après analyse du problème j'ai trouvé que la méthode "OPTIONS" n'est plus autorisée par l'API ( ça marchait avant)

![image](https://user-images.githubusercontent.com/1775843/51667044-68dc6680-1fbf-11e9-8047-20c89bc2e979.png)
 
vous remarquerez qu'on a maintenant 

**allow: GET** au lieu de **allow: GET, OPTIONS**

**Comment by jdesboeufs** [comment]
Bonjour,

Notre configuration `Access-Control` n'a pas changé récemment et en effet seuls les GET sont autorisés sur le point d'entrée `/search` (ce qui n'est pas le cas de `/search/csv` qui autorise `OPTIONS`).
Si votre navigateur tente de faire un _preflight_ c'est probablement parce que vous tentez d'envoyer des cookies. Il faut désactiver ce comportement.

**Comment by bmarwane** [comment]
Bonjour, Merci  pour votre réponse rapide.

je n'envoi pas de cookie par contre vous m'avez dirigé vers la solution :)

en effet j'avais une configuration qui rajoute un token jwt en Header dans toutes mes requettes ajax, du coup l'api ne répondait plus depuis que j'ai rajouté mon système d'authentification.

je croyais que le navigateur envoyait les preflights systématiquement, c'est pourquoi j'ai supposé qu'il y a eu un changement, merci pour l'info.

** Note pour les personnes qui utilisent axios pour faire des XHR**

évitez d'ajouter votre token JWT ( si vous en avez) par défaut d'axios, voici la cause de mon erreur:

```js
import axios from 'axios';
... 
axios.defaults.headers.common['Authorization'] = 'Bearer ' + token;
```

**Comment by jdesboeufs** [comment]
Dans cet [article détaillé](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) sont expliqués les deux modes pour le ce qu'on appelle le _Cross-Origin Resource Sharing_.

Pour les requêtes `GET`, le _preflight_ n'est pas nécessaire puisque la requête n'est pas censée effectuer des changements distants. Le navigateur fait donc la requête, mais ne vous renvoie la réponse que si les _headers_ sont conformes à ses attentes.
Pour une requêtes en écriture (`POST`, `PUT`, `PATCH`, `DELETE`…) il fait d'abord une requête `OPTIONS` pour récupérer ces informations.
