### ISSUE TITLE
Mise à jour des dépendances

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/adresse.data.gouv.fr#226]
Nous avons beaucoup de retard côté dépendances !

<img width="1071" alt="capture d ecran 2019-02-01 a 12 10 46" src="https://user-images.githubusercontent.com/1231232/52119780-8c845a00-261a-11e9-936c-394577245a5f.png">

**Comment by jdesboeufs** [comment]
Peut-être en profiter pour faire du ménage aussi.

**Comment by tusbar** [comment]
J’utilise [dependabot](https://dependabot.com) sur [geo.data.gouv.fr](https://github.com/etalab/geo.data.gouv.fr) qui passe une fois par semaine. Il peut mettre automatiquement à jour les dépendances de sécurité, etc.

Mes settings sur geo.data.gouv.fr:
<img width="533" alt="deps" src="https://user-images.githubusercontent.com/166147/52120969-5b0d8d80-261e-11e9-973d-43b4e4e4030b.png">

Le seul _inconvénient_ c’est que ça va ouvrir une PR par dependance.

**Comment by jdesboeufs** [comment]
Dommage pour les PR, on va perdre les derniers utilisateurs qui nous suivent.
Mais bon, allons-y.

**Comment by tusbar** [comment]
✅
