### ISSUE TITLE
Ajouter un formulaire de signalement

### ISSUE THREAD

**Issue by yohanboniface** [etalab/adresse.data.gouv.fr#25]
A mettre dans la page "Contribuer", à la place du lien vers le site du SNA.
Message à envoyer au SNA (courriel visible dans la page de support du SNA).
Champ email de contact obligatoire.

**Comment by yohanboniface** [comment]
@cquest je te laisse relire/adapter rapidos les wordings, notamment le texte des emails?
Je mettrai en prod ensuite. C'est toi notre correspondant "comité éditorial", après tout :p

**Comment by cquest** [comment]
ça semble ok...

**Comment by yohanboniface** [comment]
C'est en prod et opérationnel.
