### ISSUE TITLE
Afficher date de mise à jour des fichiers BAN téléchargeables

### ISSUE THREAD

**Issue by cquest** [etalab/adresse.data.gouv.fr#27]
En lien avec https://github.com/etalab/ban-data/issues/49

A afficher sur la page /download

Prendre la date actuelle du fichier téléchargeable.

**Comment by yohanboniface** [comment]
La date de modification du fichier n'est pas forcément la date de mise à jour des données. Ce serait pas mieux d'avoir une date de livraison quelque part? Genre quand tu finis tes scripts tu me mets un fichier 'xxxpouet' qui contient la date en question?

**Comment by yohanboniface** [comment]
Suis con, on a pas accès au fichier depuis l'application :/

**Comment by yohanboniface** [comment]
Voilà, mieux :)
