### ISSUE TITLE
Coordonnées géographiques

### ISSUE THREAD

**Issue by FAVAROS** [etalab/adresse.data.gouv.fr#292]
Bonjour,
lors du géocodage, les coordonnées retournées sont uniquement celles en Lambert 93 et les colonnes de coordonnées géographiques - appelées X et Y dans le descriptif des données - n'apparaissent pas.
Pourquoi ? Y a t'il une manipulation à faire lors du dépôt du fichier csv ?
Merci de votre réponse.

**Comment by jdesboeufs** [comment]
Le géocodage CSV ne retourne que les coordonnées WGS-84.
