### ISSUE TITLE
Permettre un téléchargement sur un seul département

### ISSUE THREAD

**Issue by cquest** [etalab/adresse.data.gouv.fr#30]
Choix du département dans le formulaire et lien envoyé ne serait que pour ce département.

**Comment by yohanboniface** [comment]
Tu veux #29 ou #30 en prio? :)

**Comment by yohanboniface** [comment]
Autre question: les fichiers par département existent?

**Comment by cquest** [comment]
Plutôt #29 ça a été plus demandé et c'est vraiment une nouvelle feature alors que #30 est du confort... et ça me laisse le temps de préparer les fichiers.
