### ISSUE TITLE
Ajouter la couche des routes sur l'interface de crowdsourcing.

### ISSUE THREAD

**Issue by cquest** [etalab/adresse.data.gouv.fr#31]
Nom du layer Géoportail: TRANSPORTNETWORKS.ROADS

Je l'ajoute à notre clé d'API, car il n'y est pas actuellement (c'est fait).
J'ai aussi activé la couche cadastre si on veut basculer entre les deux.

**Comment by yohanboniface** [comment]
Tu fais comment pour l'ajouter? Je voudrais bien l'ajouter sur ma clé de dev aussi, mais je comprends nada à l'interface.

**Comment by yohanboniface** [comment]
Ou bien ajouter localhost sur la clé de prod.

**Comment by cquest** [comment]
Je l'ai ajoutée sur les deux clé que j'avais généré, celle en prod et celle
pour test sur localhost.

Le 2 juillet 2015 15:52, Yohan Boniface <notifications@github.com> a écrit :

> Ou bien ajouter localhost sur la clé de prod.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/etalab/adresse.data.gouv.fr/issues/31#issuecomment-118039712>
> .
>



-- 
Christian Quest - OpenStreetMap France

**Comment by yohanboniface** [comment]
Tu peux m'envoyer celle pour localhost? Avec la mienne, ça marche pas.

**Comment by cquest** [comment]
J'ai ajouté ça sur la clé "localhost" que je t'avais créé. ça ne passe pas ?
Je passe sur IRC ;)
