### ISSUE TITLE
Crowdsourcing: ajouter mention du nom de commune et code insee

### ISSUE THREAD

**Issue by cquest** [etalab/adresse.data.gouv.fr#32]
par exemple en haut du formulaire de droite... histoire d'avoir un peu de contexte... voire:
Val-de-Marne (94)
  Saint-Maur-des-Fossés (code INSEE 94068)

**Comment by yohanboniface** [comment]
Done in https://github.com/etalab/adresse.data.gouv.fr/commit/535bbd6c09fab1db2cca7cc85175db3a47f4ee1d
