### ISSUE TITLE
Formatage non identique pour les arrondissements de Paris

### ISSUE THREAD

**Issue by baloran** [etalab/adresse.data.gouv.fr#33]
Hello, 

Lorsque l'on tape sur l'api avec l'url http://api-adresse.data.gouv.fr/search?q=paris+1er+arr la city, le label et le name n'affiche pas Paris puis sont arrondissement à contrario de http://api-adresse.data.gouv.fr/search?q=marseille+1er+arr qui marque bien Marseille devant.

**Comment by yohanboniface** [comment]
Ça me semble un problème de données, je passe la balle à @cquest  (pour info, quand il s'agit des données, c'est plutôt à voir du côté de https://github.com/etalab/ban-data/issues à l'avenir ;) )

**Comment by cquest** [comment]
Ces requêtes ne correspondent pas à des adresses (manque au minimum un nom de voie ou de lieu dit).
Notre géocodeur n'est pas adapté à ce type de recherche.
