### ISSUE TITLE
Possibilité de mettre plusieurs filtres

### ISSUE THREAD

**Issue by baloran** [etalab/adresse.data.gouv.fr#34]
Serait-ce possible de pouvoir restreindre la recherche à plusieurs `filtre`, par exemple type `street` et `city` avec l'API.

**Comment by yohanboniface** [comment]
Aujourd'hui non, et c'est pas facile à implémenter. Mais oui c'est quelque chose qu'on veut faire :)

Par ailleurs, le `OR` (i.e. type=city OR type=street) sera sûrement implémenté avant le `AND` (i.e. type=city AND postcode=01000), plus compliqué à mettre en œuvre en l'état des algos.

(Pour info, cette fois, c'est le module addok qui est en cause: https://github.com/etalab/addok ;) )

**Comment by baloran** [comment]
Merci. J'y penserai pour la prochaine fois :)
