### ISSUE TITLE
API injoignable si la requête HTTP ne contient pas de "Host:"

### ISSUE THREAD

**Issue by cquest** [etalab/adresse.data.gouv.fr#35]
Revoir le routage par nginx en front pour prendre en compte /search (et autres) directement ?

**Comment by yohanboniface** [comment]
humm, mais vu qu'il y a plusieurs hosts sur le même serveur, tu voudrais faire comment? Un seul peut être mis en default :/

**Comment by cquest** [comment]
Mettre soit l'API en default, soit router vers l'API si la query commence par /search (et autres)

**Comment by cquest** [comment]
Ceci ne touche que les appels faits en HTTP/1.0 sans champ "Host"... qu'on peut considérer obsolète vu qu'HTTP/1.1 est légalement majeur (plus de 18 ans) et impose l'utilisation du champ "Host".
