### ISSUE TITLE
"unknown encoding utf-8-sig"

### ISSUE THREAD

**Issue by blag001** [etalab/adresse.data.gouv.fr#369]
Problème lors de l'appel de /search/CSV/ 

Si le 4096 octet du fichier est un accent utf-8 (multi-octet, sur le 4096 et le 4097 donc) on sort en erreur avec :

`{"title": "Unknown encoding utf-8-sig", "description": "Unknown encoding utf-8-sig"}`

**Comment by 13cailla** [comment]
Problème similaire de mon côté.

**Comment by jdesboeufs** [comment]
Avez-vous testé le même fichier avec l'interface ?
Il y a un pré-traitement côté navigateur qu'on pourrait mettre en place directement sur l'API.

**Comment by jdesboeufs** [comment]
Corrigé.

**Comment by icdc-jeremy** [comment]
Bonjour,

Nous avons ce souci sur une installation Docker de Addok (image en latest).

Existe-t-il une image avec ce fix ?

D'avance merci :)

**Comment by guillaumevoyau** [comment]
Nous avons aussi rencontré le problème qui semble avoir été corrigé [ici](https://github.com/addok/addok-csv/commit/7957042f36213423a0a754b779dbb7b7f854d413) dans la dernière version de addok-csv 1.1.0
