### ISSUE TITLE
Récupération d'une bbox

### ISSUE THREAD

**Issue by jeanpul** [etalab/adresse.data.gouv.fr#37]
Bonjour,

Merci pour ce service, l'API est claire et simple à utiliser. Je voudrais savoir si il sera possible
de récupérer une "bounding box" comme c'est le cas sur Nominatim par exemple afin de faciliter 
le choix du zoom sur les cartes (Leaflet et autres).

Merci 
Cdt
Fabien

**Comment by parville** [comment]
Bonjour, il me semble qu'on s'éloigne du coeur du sujet ? On tombe là dans du spatial pur : quel est le rectangle englobant de ces N points ?!

**Comment by jeanpul** [comment]
Bonjour,

Dans le cas on l'on retourne une adresse complète (type housenumber), je veux bien admettre qu'elle soit modélisée par un point 2D (lat, lon) mais dans le cas ou l'API me retourne un type "city" ou "street" ? Je me posais simplement la question de la qualité de la position 2D lorsque j'ai une adresse qui fait référence à une zone assez large.

Cdt

Fabien

**Comment by parville** [comment]
Bonjour, merci pour la reformulation ! Je n'avais vu la question sous cet angle mais sous l'angle de l'emprise globale d'une multi réponse de points (donc potentiellement géo-étendue). 

On sort vraiment du cadre strict, sauf à considérer que l'étendue du commune est reconstituée par le MBR des points d'adresse de la commune, idem pour les rues (algo déjà utilisé pour centrer la carte sur "une rue" sur le site). 

Je comprends la question.

**Comment by jeanpul** [comment]
C'est vrai que mon exemple du zoom sous Leaflet n'était peut être pas bien choisi, ma question était effectivement d'ordre plus général

Cdt

**Comment by cquest** [comment]
On peut aussi ajuster le zoom sur le client en fonction du type, par exemple :
- housenumber: 18
- street/locality: 16
- village/city: 12

**Comment by jdesboeufs** [comment]
Ces questions sont plus des problématiques d'implémentation côté client.
Dans tous les cas récupérer les contours d'une commune est possible via l'[API Géo](https://geo.api.gouv.fr).

Si le besoin est encore présent, merci de nous le signaler et nous ouvrirons à nouveau cette discussion.
