### ISSUE TITLE
reverse ne donne pas la même adresse que search

### ISSUE THREAD

**Issue by lsaudon** [etalab/adresse.data.gouv.fr#377]
Bonjour,
Si je recherche
`https://api-adresse.data.gouv.fr/search/?q=60 rue de la liberté 38180 Seyssins`
je trouve les coordonnées suivante`"coordinates": [5.696633, 45.16589]`
Si je recherche `https://api-adresse.data.gouv.fr/reverse/?lon=5.69663&lat=45.16589&limit=5`.
Je ne retrouve pas le 60 rue de la liberté 38180 Seyssins
Je trouve le 58 rue de la liberté 38180 Seyssins.
Ils ont les mêmes coordonnées.
Je devrais trouvé les deux dans la liste.

**Comment by cquest** [comment]
Ces deux adresses sont exactement à la même position lat/lon.

Une issue ouverte sur le moteur d'addok explique le comportement: https://github.com/addok/addok/issues/545

Une seule adresse est retournée dans une voie/lieu-dit donné, la plus proche... mais aussi la première trouvée (donc le 58 avant le 60).

Correction à suivre sur https://github.com/addok/addok/issues/545

**Comment by lsaudon** [comment]
Merci pour les détails.
