### ISSUE TITLE
Echec

### ISSUE THREAD

**Issue by yoann34** [etalab/adresse.data.gouv.fr#38]
Bonsoir
Mon fichier ne passe pas, j'ai un message :
Oops, quelque chose tourne pas rond… Si cela persiste, vous pouvez signaler une erreur.

Mon fichier fait 83615 lignes en UTF8 pour 5,5Mo
Même message sur firefox, chrome, iexplorer

Si vous avez une idée ?

Merci pour votre aide

Bien cordialement

Ajout 19h45 : Découpé en deux fichiers de 40 000 lignes cela plante mais découpé en 4 fichiers de 20 000 lignes cela passe. Pourtant la limite est bien de 8Mo, non ? Merci par avance

**Comment by yohanboniface** [comment]
> Ajout 19h45 : Découpé en deux fichiers de 40 000 lignes cela plante mais découpé en 4 fichiers de 20 000 lignes cela passe. Pourtant la limite est bien de 8Mo, non ?

Il me semble bien oui, mais c'est peut-être un timeout. Au bout de combien de temps le message apparaît-il?

**Comment by yoann34** [comment]
Bonjour
Merci pour votre réponse, en effet le message apparait après 5 minutes
Est il possible de rallonger ce timeout ?
Bien cordialement

**Comment by yohanboniface** [comment]
>  Est il possible de rallonger ce timeout ?

Je suis pas sûr que ce soit la solution: on va augmenter le timeout une fois, puis quelqu'un d'autre touchera cette limite, puis on augmentera de nouveau, etc. ;)
De mon point de vue, 5 minutes de timeout c'est cohérent.
Découper les fichiers quand on dépasse ce seuil me semble acceptable (ou bien installer sa propre instance d'addok et avoir un timeout plus élevé ou taper en local mais c'est un autre débat ;)).
En revanche, il faudrait un message d'erreur plus explicite.

@cquest augmenter le timeout, t'en penses quoi?

**Comment by cquest** [comment]
Même avis que @yohanboniface augmenter le timeout n'est pas la solution, découper les fichiers en lots de 10000 est la bonne option.
