### ISSUE TITLE
Geocoder CSV

### ISSUE THREAD

**Issue by laurenthembord** [etalab/adresse.data.gouv.fr#39]
Bonjour,

Le Geocoder CSV ne fonctionne pas, ou je ne sais pas l'utiliser.
J'ai mis un fichier CSV BAN dans le Geocoder CSV.
Il se lance, puis s'arrête, se relance, et enfin se met en erreur.

Qu'ai-je mal fait ?

**Comment by yohanboniface** [comment]
Difficile à dire sans plus de détails.
Puis-je avoir accès au fichier en question?

**Comment by laurenthembord** [comment]
Oui, bien-sûr à cette adresse (seule solution)
https://adresse.data.gouv.fr/download/2c620d2e

Le dossier que j'ai essayé d'utiliser est 
BAN_licence_gratuite_repartage_56

**Comment by yohanboniface** [comment]
430000 lignes et 70 Mo, c'est un peu trop d'un coup ;)
Les limites sont taille max 6Mo et timeout à 600 secondes, donc il faut viser autour de 10000 lignes.
Il faudrait, si c'est pas déjà le cas, qu'on affiche explicitement ces limites sur la page.

Par ailleurs, on est d'accord que ces fichiers contiennent déjà les données géo et que, à part pour l'exercice, ça ne sert à rien de les regéocoder? :)

Aussi, pour info, les fichiers sont accessibles séparément (en licence ODBL) ici http://bano.openstreetmap.fr/BAN_odbl/

**Comment by laurenthembord** [comment]
Merci pour ces précisions.
