### ISSUE TITLE
Le copier/coller ne lance pas l'autocomplétion

### ISSUE THREAD

**Issue by cquest** [etalab/adresse.data.gouv.fr#4]

**Comment by yohanboniface** [comment]
Works for me.

Sur ton Ubuntu avec FF?

**Comment by cquest** [comment]
Sur mon Chrome OSX...

Le 27/02/2015 11:24, Yohan Boniface a écrit :
>
> Works for me.
>
> Sur ton Ubuntu avec FF?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/etalab/adresse.data.gouv.fr/issues/4#issuecomment-76371452>.
>

-- 
Christian Quest - OpenStreetMap France

**Comment by cquest** [comment]
Ca marche maintenant sur mon Chrome OSX...
