### ISSUE TITLE
souhait de pouvoir avoir accès aux coordonnées du point géolocalisé dans la carte interactive

### ISSUE THREAD

**Issue by FERRATON** [etalab/adresse.data.gouv.fr#40]
Saisir une adresse, la carte se positionne sur le point dans la rue, mais nous n'avons pas accès aux coordonnées X,Y du point.

**Comment by cquest** [comment]
La carte interactive n'est qu'un exemple d'implémentation de saisie avec autocomplétion.
Elle n'a pas vocation à être utilisée au delà de son côté démonstration.

PS: ces coordonnées sont visibles dans l'URL une fois une adresse sélectionnée
