### ISSUE TITLE
Avoir la ville sans l'arrondissment

### ISSUE THREAD

**Issue by lsaudon** [etalab/adresse.data.gouv.fr#400]
ça serait bien d'avoir la ville avec et sans l'arrondissement si il en existe un.

**Comment by jdesboeufs** [comment]
Bonjour,

Pouvez-vous préciser votre demande ?

**Comment by lsaudon** [comment]
`https://api-adresse.data.gouv.fr/search/?q=100%20Rue%20Marcadet`
le champ city = "Paris 18e Arrondissement".
Est-il possible d'avoir le champ city = "Paris"
et district = "18e Arrondissement"  ?

**Comment by jdesboeufs** [comment]
Un tel changement obligerait à créer une nouvelle version de l'API.
Mais on peut imaginer ajouter deux champs optionnels :
- `maincity`: `Paris`
- `district`: `18e Arrondissement`

**Comment by lsaudon** [comment]
ça me va également.

**Comment by Fabback** [comment]
Etant peut-être à l'origine de la demande d'affichage des arrondissements je me permet de rebondir.

Lors de la recherche (non-filtrée sur un type), ex : "**http://api-adresse.data.gouv.fr/search/?q=75018%20paris**", les résultats de type "streets" nous sont bien retournés avec **city="paris"** et **district="Paris 18e Arrondissement"**, or les résultats de type "municipality" nous sont retournés avec **city="Paris 18e Arrondissement"** et sans champs **"district"**. 

Je pense (mais ce n'est que mon avis) que standardiser la 1ere forme nous permet de traiter les retours à l'envie (avec ou sans le nom de l'arrondissement) et sans manque d'information pour autant. Même si "district" ne devrait contenir que "18e arrondissement".

Par ailleurs, si je m'en tiens à ma recherche "75018 Paris", il est retourné actuellement un "Paris 75001" alors qu'il contient l'INSEE de "Paris 75000" (le 75056) au lieu de celui du 1er arrondissement (75101), ça me parait assez trompeur (pour ne pas dire erroné)

Bonne journée (et merci pour les ajouts des arrondissements, ça me permettra de retirer les developpements "patch" qui étaient nécessaire à mon activité)

**Comment by jdesboeufs** [comment]
L'ajout de l'arrondissement dans le champ `city` était un problème critique pour ameli.fr donc nous avons fait marche arrière, et en avons profité pour créer le champ `district` dont on parlait au dessus.

**Comment by jdesboeufs** [comment]
(mais uniquement sur `street` et `housenumber`)

**Comment by Fabback** [comment]
> L'ajout de l'arrondissement dans le champ `city` était un problème critique pour ameli.fr donc nous avons fait marche arrière, et en avons profité pour créer le champ `district` dont on parlait au dessus.

J'ai justement ce problème lorsqu'il s'agit de recherche "municipality" seulement, faute de mieux j'ai patché et épuré tout ce qui est rattaché à Paris/Lyon/Marseille pour déplacer l'arrondissement de "city" vers "district", et standardiser les retours. Si ce n'est pas intégré en l'état sur l'API ça ne me gène pas (j'ai patché), je faisait juste une proposition pour la cohérence des retours.
