### ISSUE TITLE
Changement de retour API sur requête sur postcode sur Toulouse

### ISSUE THREAD

**Issue by eturck** [etalab/adresse.data.gouv.fr#419]
Bonjour à tous,

Avant toute chose merci pour le travail effectué sur cette API, c'est vraiment top d'avoir quelque chose d'aussi qualitatif à disposition.

Nous faisons des requêtes de ce type à l'API : https://api-adresse.data.gouv.fr/search/?type=municipality&q=31300&limit=1000 ce qui retourne actuellement ceci : 

![retour_api](https://user-images.githubusercontent.com/5136553/63603617-48fb3880-c5ca-11e9-8e90-419069be5bd3.png)

Le problème, que nous n'avions pas auparavant, c'est que même si `Toulouse` est bien retournée elle est retournée avec le postcode `31500`. Auparavant une requête avec `31300` retournait Toulouse en `31300`, `31200` retournait `31200`... et de même pour les 4 autres codes. Maintenant nous avons toujours `31500` quelque que soit le param en entrée.

J'ai cherché à voir si des changements avaient été effectué sur l'import de ce type de ville mais je n'ai rien vu. J'ai constaté que le même comportement était présent sur Orléans, Nantes... Toutes les villes pour lesquelles plusieurs codes postaux sont sur un seul et même code INSEE 😃 

Nous avons constaté le problème le 22 juillet (nous avons mis un place quelque chose pour contourner le problème), mais j'ai un peu traîné pour faire une issue... Est-ce un bug ou une modification volontaire de la gestion de ce type de villes ? 

Bonne journée.

**Comment by cquest** [comment]
Le changement de comportement provient d'un changement dans les données servies par l'API.

Cette API n'est pas de tout conçue pour faire une simple recherche par code postal. Pour cela il faut plutôt se tourner vers https://geo.api.gouv.fr/decoupage-administratif/communes

**Comment by eturck** [comment]
Bonjour,

Je ne sais pas pourquoi adresse.data.gouv.fr à l'origine avait été choisi. Nous avions pris connaissance de geo.api.gouv.fr il y a un an ou deux mais nous avions rencontré d'autres soucis ce qui fait que le changement n'avait pas été fait. Principalement etalab/api-geo#60 et etalab/api-geo#97.

Mais pour faire les choses proprement ça sera tout de même mieux de passer sur geo.api un jour :).

Merci pour toutes ces informations.
