### ISSUE TITLE
souhait de conserver les adresses dans la carte interactive

### ISSUE THREAD

**Issue by FERRATON** [etalab/adresse.data.gouv.fr#42]
Dans l'outil carte interactive, quand l'outil propose plusieurs adresses, si on clique sur l'une des adresses, il est impossible de revenir sur la liste des propositions précédentes. Il faut alors resaisir l'adresse.

**Comment by cquest** [comment]
La carte interactive n'est qu'un exemple d'implémentation de saisie avec autocomplétion.
Elle n'a pas vocation à être utilisée au delà de son côté démonstration.
