### ISSUE TITLE
souhait de disposer d'autres fonds dans la carte interactive et zoom maxi plus grand

### ISSUE THREAD

**Issue by FERRATON** [etalab/adresse.data.gouv.fr#43]
zoom maxi plus grand sur la carte interactive

possibilité d'ajouter autres fonds de plan : orthophotos,...

**Comment by cquest** [comment]
La carte interactive n'est qu'un exemple d'implémentation de saisie avec autocomplétion.
Elle n'a pas vocation à être utilisée au delà de son côté démonstration.
