### ISSUE TITLE
Problème géocodage base officielle des codes postaux

### ISSUE THREAD

**Issue by EricWaltR** [etalab/adresse.data.gouv.fr#45]
Bonjour, j'ai cherché à géocoder via cette page http://adresse.data.gouv.fr/csv/ le fichier du groupe La Poste qu'on trouve ici : http://datanova.opendatasoft.com/explore/dataset/laposte_hexasmal/?disjunctive.code_commune_insee&disjunctive.nom_de_la_commune&disjunctive.code_postal&disjunctive.libell_d_acheminement&disjunctive.ligne_5

A deux reprises cela me renvoit une erreur. Fausse manip de ma part ou autre raison ? Le fichier fait 1,5 megas, j'ai testé avec et sans paramétrage des paramètres avancés sans succès, avec une sélection partielle ou totale des colonnes à utiliser parmi les colonnes dispos, sans succès également.

Quand je clique "lancer" la barre d'acheminement se positionne directement à 100%, puis temps de latence, puis message d'erreur "Oops, quelque chose tourne pas rond… Si cela persiste, vous pouvez signaler une erreur.". Donc je signale ;)

Configuration standard connexion personnelle sans proxy via box FAI. Mac OS X Yosemite / Chrome Version 49.0.2623.87 (64-bit).

Merci d'avance de vos informations et aide, 

Cordialement,

Eric

**Comment by cquest** [comment]
Le fichier des codes postaux ne contient aucune adresse, seulement les codes postaux. Il n'est pas géocodable avec notre API.

De plus, les codes postaux ne sont pas une description géographique, vu qu'ils peuvent s'étendre sur plusieurs communes et à l'inverse plusieurs codes postaux peuvent recouvrir une même commune (y compris sur la même zone géographique).

Il ne correspondent qu'à l'organisation de la distribution du courrier.
