### ISSUE TITLE
Import CSV ne fonctionne pas

### ISSUE THREAD

**Issue by mlecorreCMAR** [etalab/adresse.data.gouv.fr#47]
Bonjour,

Je ne parviens à géocoder mon fichier d'adresse .csv. Le message OOps, etc... s'affiche inlassablement.

**Comment by yohanboniface** [comment]
> Je ne parviens à géocoder mon fichier d'adresse .csv. Le message OOps, etc... s'affiche inlassablement.

Sans plus d'info il va nous être difficile de vous être utiles.
Peut-on par example avoir le fichier en question?

**Comment by mlecorreCMAR** [comment]
☺ je me doute…

[CMAR REGION PAYS DE LA LOIRE-QUADRI]


Marion LE CORRE
Chargée d'études - Observatoire
6 boulevard des Pâtureaux – 44985 SAINTE-LUCE/LOIRE Cedex
• 02 51 13 31 36 - 6 02 51 13 31 31
mlecorre@artisanatpaysdelaloire.fr<mailto:mlecorre@cm-nantes.fr>



De : Yohan Boniface [mailto:notifications@github.com]
Envoyé : mercredi 13 avril 2016 16:57
À : etalab/adresse.data.gouv.fr
Cc : LE CORRE Marion
Objet : Re: [etalab/adresse.data.gouv.fr] Import CSV ne fonctionne pas (#47)


Je ne parviens à géocoder mon fichier d'adresse .csv. Le message OOps, etc... s'affiche inlassablement.

Sans plus d'info il va nous être difficile de vous être utiles.
Peut-on par example avoir le fichier en question?

**Comment by mlecorreCMAR** [comment]
Le format des cellules semblait être incompatible. J'ai contournée mon problème en réimportant autrement mes adresse dans un autre fichier .csv vierge: çà fonctionne.
Merci quand même!
