### ISSUE TITLE
Oops, quelque chose tourne pas rond !

### ISSUE THREAD

**Issue by ghost** [etalab/adresse.data.gouv.fr#48]
Bonjour,

J'ai un problème lors de l'import d'un fichier CSV afin de créer une cartographie, le message d'erreur suivant s'affiche "Oops, quelque chose tourne pas rond"...
Le fichier est un tableur, lisible avec l'encodage "iso-8859-1". Il comporte 215 lignes, dont des adresses mails, des numéros de téléphones ainsi que des adresses.

N'hésitez pas à me contacter si vous souhaitez plus d'infos !

Merci d'avance pour votre aide !!

Jennifer

**Comment by yohanboniface** [comment]
Bonjour,

Je veux bien si c'est possible une copie du fichier CSV en question. Si ce sont des données sensibles, par mail yohan point boniface arobase data point gouv point fr.

Merci :)

**Comment by lauraPDS** [comment]
Bonjour, 
J'ai le même problème et je ne sais pas comment le résoudre...
Lorsque je lance le géocodage après avoir téléchargé le fichier csv (tout s'affiche correctement), le message : "Oops, quelque chose tourne pas rond…" s'affiche.
Avez-vous une solution? des points particuliers à vérifier ?

Merci d'avance pour votre aide.

Cordialement,

Laura

**Comment by marie-ypresia** [comment]
Bonjour, 
je rencontre moi aussi ce problème-là. j'ai essayé en enlevant les retour chariot dans mes adresses, en faisant différents types de csv, avec un nombre limité de données. Rien à faire, toujours le même message d'erreur. Je vous ai envoyé un fichier test la semaine  dernière. Avez-vous pu jeter un oeil ? 
En vous remerciant, 
Cordialement, 
Marie

**Comment by ksoumare** [comment]
bonjour,

J'ai un problème lors de l'import d'un fichier CSV afin de créer une cartographie, le message d'erreur suivant s'affiche "Oops, quelque chose tourne pas rond"...
Le fichier est un excel que j'ai enregistré en CVS, lisible avec l'encodage "UTF 8". Il comporte 38 lignes, dont des adresses mails, des numéros de téléphones ainsi que des adresses.

N'hésitez pas à me contacter si vous souhaitez plus d'infos !

Merci d'avance pour votre aide !!

**Comment by cquest** [comment]
Pour nous permettre d'investiguer, merci d'envoyer le fichier CSV récalcitrant à adresse@data.gouv.fr
