### ISSUE TITLE
Géo-codage CSV (/search/csv/) liste code postaux ne marche plus

### ISSUE THREAD

**Issue by PLsergent** [etalab/adresse.data.gouv.fr#506]
Bonjour,

Je souhaite passer une liste de code postaux grâce à un fichier CSV afin de réaliser un géocodage, mon fichier ressemble à cela:
```
address
29200
29200
29200
29200
```

Auparavant la requête me renvoyait quelque chose comme ça: 👍 
```
address|latitude|longitude|result_label|result_score|result_type|result_id|result_housenumber|result_name|result_street|result_postcode|result_city|result_context|result_citycode|result_oldcitycode|result_oldcity|result_district
29200|48.406102|-4.498893|Brest|0.41|municipality|29019||Brest||29200|Brest|29, Finistère, Bretagne|29019|||
29200|48.406102|-4.498893|Brest|0.41|municipality|29019||Brest||29200|Brest|29, Finistère, Bretagne|29019|||
29200|48.406102|-4.498893|Brest|0.41|municipality|29019||Brest||29200|Brest|29, Finistère, Bretagne|29019|||
29200|48.406102|-4.498893|Brest|0.41|municipality|29019||Brest||29200|Brest|29, Finistère, Bretagne|29019|||
```

Cependant depuis les derniers commit la requête me renvoie quelque chose de différent: 👎 
```
address,latitude,longitude,result_label,result_score,result_type,result_id,result_housenumber,result_name,result_street,result_postcode,result_city,result_context,result_citycode,result_oldcitycode,result_oldcity,result_district
29200,,,,,,,,,,,,,,,,
29200,,,,,,,,,,,,,,,,
29200,,,,,,,,,,,,,,,,
29200,,,,,,,,,,,,,,,,
```

Voici à quoi ressemble ma requête:
```
curl -X POST -F data=@./src/data_csv/addresses.csv https://api-adresse.data.gouv.fr/search/csv/
```

Pouvez-vous me dire d'où vient l'erreur ?

**Comment by jdesboeufs** [comment]
Bonjour,

Premier point, ce géocodeur est conçu pour travailler sur des adresses relativement complètes, et non des codes postaux seuls. On ne garantie aucun résultat pour ce cas de figure.
Je rappelle aussi qu'un code postal correspond potentiellement à PLUSIEURS communes, il n'y a d'ailleurs que 6000 codes postaux, contre 35000 communes.

On va néanmoins regarder ce qu'il se passe !

**Comment by PLsergent** [comment]
Merci pour votre réponse rapide !
Dans le cadre de mon application je n'ai pas besoin de plus de précision.
Aussi, je viens de tester avec une adresse complète et ça ne marche pas non plus !

```
address
55 Rue du Faubourg Saint-Honoré 75008 Paris
```

**Comment by jdesboeufs** [comment]
Dans ce cas utilisez l'API Géo Découpage administratif, ou le fichier de mapping codes postaux communes :)

**Comment by jdesboeufs** [comment]
Concernant le bug, c'est l'absence de délimiteur de colonne qui fait échouer la détection automatique. Je vais regarder pour corriger ça.

**Comment by jdesboeufs** [comment]
Problème corrigé en production !

**Comment by PLsergent** [comment]
Merci beaucoup !
