### ISSUE TITLE
"Quelque chose ne tourne pas rond" : caractère accentué dans le nom du fichier géocodé

### ISSUE THREAD

**Issue by chezrom** [etalab/adresse.data.gouv.fr#51]
Quand le nom du fichier à géocoder comprend des caractères accentués, le géocodage échoue avec le fameux message d'erreur "Quelque chose ne tourne pas rond".
Virer les dits caractères du nom permet de traiter le csv à géocoder.

**Comment by jdesboeufs** [comment]
Corrigé via #85.
Je ferme mais n'hésitez pas à revenir vers nous en cas de problème.
