### ISSUE TITLE
Retrouver une commune avec le seul citycode

### ISSUE THREAD

**Issue by bdavidxyz** [etalab/adresse.data.gouv.fr#533]
concernant l'API https://api-adresse.data.gouv.fr/search/ , le citycode (code commune en français) est l'identifiant unique d'une commune, il est donc logique de pouvoir retrouver une commune à partir de son citycode. Le problème est que le paramètre "q" (query) est obligatoire, il est donc impossible de demander _uniquement_ une commune à partir du citycode. La requête la plus proche consiste à rentrer q=rue&citycode=02004 par exemple; Cela marche pour la commune 02004 (Agnicourt-et-Séchelles), mais impossible de retrouver Saint-Pierre-Le-Vieux (71469).

**Comment by jdesboeufs** [comment]
Et pourquoi ne pas utiliser l'API Géo Découpage administratif dans ce cas ?
https://geo.api.gouv.fr/communes/71469

La doc est ici : https://geo.api.gouv.fr

L'API Géo "Adresses" c'est pour les adresses :)
