### ISSUE TITLE
Rediriger la page /api

### ISSUE THREAD

**Issue by tmerlier** [etalab/adresse.data.gouv.fr#534]

**Comment by jdesboeufs** [comment]
On l'a pas fait déjà ?

**Comment by tmerlier** [comment]
Effectivement ! L'erreur que j'ai vu vient du fait que l'on envoi toujours https://geo.api.gouv.fr/adresse au composant `<Link>` Next dans le header  et dans la page `/tools`.

La redirection ne doit pas être utilisé pour le moment.
