### ISSUE TITLE
Fichier d'adresseimpossible à geocoder 

### ISSUE THREAD

**Issue by phjarry** [etalab/adresse.data.gouv.fr#54]
Je ne parviens pas à géocoder le fichier en pièce jointe, pourtant le format à l'air correct.
Ai-je fait une mauvaise manipulation ?
[liste médecins Ivry AMELI -pour adresse geocodage.zip](https://github.com/etalab/adresse.data.gouv.fr/files/571078/liste.medecins.Ivry.AMELI.-pour.adresse.geocodage.zip)

Merci de votre aide
Philippe Jarry
06 67 44 93 87
pjarry@ivry94.fr

**Comment by yohanboniface** [comment]
@phjarry enlève l'accent dans le nom du fichier. :)
Sera corrigé dans la prochaine version (qui traîne…) ;)

**Comment by phjarry** [comment]
Merci

2016-11-04 10:35 GMT+01:00 Yohan Boniface <notifications@github.com>:
