### ISSUE TITLE
CSV renvoyé par l'API sans séparateur de champ ?

### ISSUE THREAD

**Issue by joelgombin** [etalab/adresse.data.gouv.fr#57]
Voici le retour que j'ai sur une requête simple sur l'API CSV : 

![](http://i.imgur.com/KiwOepS.png)

Il semble ne pas y avoir de séparateur de champ dans le fichier CSV et je ne parviens pas à le parser.

Le fichier CSV (test) utilisé est disponible ici : https://www.dropbox.com/s/69cuqf1jsid6tmf/file7f657bb17096.csv?dl=0

**Comment by cquest** [comment]
C'est sûrement parce qu'il n'y a qu'une colonne.
Si tu as le code INSEE de la commune, je te conseille vivement de l'ajouter et de filtrer dessus pour obtenir les meilleurs résultats.

**Comment by joelgombin** [comment]
Oui mais je ne l'ai pas ;-) ok,c'est ce que je me suis dit aussi, je vais essayer de lui passer systématiquement deux colonnes au moins, quitte à en mettre une en dummy.

**Comment by joelgombin** [comment]
(ceci dit c'est bien un bug de l'API, on est d'accord ?)

**Comment by cquest** [comment]
Oui, bug sur https://github.com/addok/addok-csv/blob/master/addok_csv/plugin.py il faudrait créer une issue là bas... ce repo ci est dédié au site web, pas aux API qui sont derrière ;)

**Comment by joelgombin** [comment]
super, je n'arrivais pas à trouver le bon repo.

**Comment by thbar** [comment]
@joelgombin pour info j'ai fait un test, et si tu enlèves les guillemets de ta source, alors l'output est formatté comme il faut.

Avant :

```
ville"latitude"longitude"result_label"result_score"result_type"result_id"result_housenumber"result_name"result_street"result_postcode"result_city"result_context"result_citycode
Agen"44.202482"0.618546"Agen"0.97"city"47001""Agen""47000"Agen"47, Lot-et-Garonne, Aquitaine"47001
Ajaccio"41.92499"8.735937"Ajaccio"0.98"city"2A004""Ajaccio""20000"Ajaccio"2A, Corse-du-Sud, Corse"2A004
```

Après:

```
"ville","latitude","longitude","result_label","result_score","result_type","result_id","result_housenumber","result_name","result_street","result_postcode","result_city","result_context","result_citycode"
"Agen","44.202482","0.618546","Agen","0.97","city","47001","","Agen","","47000","Agen","47, Lot-et-Garonne, Aquitaine","47001"
"Ajaccio","41.92499","8.735937","Ajaccio","0.98","city","2A004","","Ajaccio","","20000","Ajaccio","2A, Corse-du-Sud, Corse","2A004"
```

Je mets la note ici par défaut, car sur addok-csv les issues sont fermées.

A bon entendeur :-)

**Comment by joelgombin** [comment]
En effet les issues sont fermées !

J'ai noté également que si on garde le csv original (avec des guillemets), mais qu'on passe explicitement à l'API un argument `delimiter`, ça marche correctement. C'est sans doute le fix le plus facile (en tout cas dans mon cas d'usage).

**Comment by davidbgk** [comment]
N'hésitez pas à déclarer les issues relative à addok et ses plugins sur [le dépôt principal](https://github.com/addok/addok/issues).
