### ISSUE TITLE
oups quelque chose ne tourne pas rond

### ISSUE THREAD

**Issue by gcarbelo** [etalab/adresse.data.gouv.fr#58]
Bonjour
J'ai un fichier csv en entrée avec le format en pièce jointe.
Je relance 3 fois le process et j'ai toujours la même erreur : oups quelque chose ne tourne pas rond

Pouvez-vous me dire d'où vient le problème?

Par avance merci et bonne journée
[20170307 - Fichier abonnés - Light - Copie.zip](https://github.com/etalab/adresse.data.gouv.fr/files/825306/20170307.-.Fichier.abonnes.-.Light.-.Copie.zip)

**Comment by yohanboniface** [comment]
Je pense que ça vient de l'accent dans le nom du fichier.
Corrigé dans la nouvelle version, bientôt en production.

**Comment by gcarbelo** [comment]
Merci!
