### ISSUE TITLE
[Explore/BAL] Problème d'encodage de certains noms de voies

### ISSUE THREAD

**Issue by cedric-famibelle-pronzola** [etalab/adresse.data.gouv.fr#580]
Le nom de certaines voies apparaît avec un encodage différent :
- **Exemples**
  - *explore*
    - https://adresse.data.gouv.fr/explore/commune/13004
    - https://adresse.data.gouv.fr/explore/commune/13097
  - *BAL*
    - https://adresse.data.gouv.fr/bases-locales/jeux-de-donnees/accm/13004
    - https://adresse.data.gouv.fr/bases-locales/jeux-de-donnees/accm/13097

- **Capture d'écran**
  - *explore*
![Capture du 2020-02-28 12-11-12](https://user-images.githubusercontent.com/45098730/75544093-8b8f4900-5a23-11ea-9a1e-1437ebd8c5cf.png)

  - *BAL*
![Capture du 2020-02-28 12-05-30](https://user-images.githubusercontent.com/45098730/75543672-a7deb600-5a22-11ea-8e0f-c5dd5942681a.png)

**Comment by tmerlier** [comment]
Ce problème d'encodage n'est plus présent sur le nouvel outil d'exploration de la BAN.
