### ISSUE TITLE
Le géocodeur CSV n'aime pas les accents dans les entête

### ISSUE THREAD

**Issue by GuyMarty-ARSOC** [etalab/adresse.data.gouv.fr#62]
Bonjour,
Et quand il en trouve il vous jette sèchement : "Oops, quelque chose tourne pas rond… Si cela persiste, vous pouvez signaler une erreur."
En espérant que cela sera utile
Guy Marty

**Comment by jdesboeufs** [comment]
Problème corrigé via #85.
Je ferme mais n'hésitez pas à revenir vers nous en cas de difficultés.
