### ISSUE TITLE
Géocodeur CSV gère difficilement les "CR" (\r) seuls en fin de ligne

### ISSUE THREAD

**Issue by GuyMarty-ARSOC** [etalab/adresse.data.gouv.fr#63]
Bonjour,
J'avais un fichier ne contenant que les "CR" (\r) en fin de ligne: 
- la partie analyse ne ligne se passe très bien,
- le géocodage n'a pas été fait, le CSV renvoyé contient toutes les données du fichier d'origine sur une seule ligne.

En espérant que cela sera utile.
Guy Marty

**Comment by cquest** [comment]
Il faut que le CSV soit cohérent en entrée, de préférence en UTF-8 pour éviter de nombreux problèmes liés à l'encodage.

L'API n'a pas vocation à remettre au propre les fichiers CSV.
