### ISSUE TITLE
Pas de géocodage CSV si précision des codes INSEE et postal 

### ISSUE THREAD

**Issue by GuyMarty-ARSOC** [etalab/adresse.data.gouv.fr#64]
Bonjour,
Avec les données du fichier joint, l'adresse est bien géocodée si on ne précise rien, si dans la partie "4. Paramètres avancés (optionnels)" on précise le code postal et le code INSEE le géocodage ne se fait pas.

A l'origine, la ligne de donnée était au milieu d'un fichier, le géocodage a été fait avec la précision maximum (numéro, type, nom de voie, ville et code INSEE et code postal dans la partie "4. Paramètres avancés (optionnels)") toutes lignes sont géocodées sauf celle là.

En espérant que cela sera utile
Guy Marty

[GHT OC ES.201705.Nimes.txt](https://github.com/etalab/adresse.data.gouv.fr/files/1088909/GHT.OC.ES.201705.Nimes.txt)

**Comment by cquest** [comment]
Il ne faut utiliser qu'un des deux filtre, de préférence celui sur le code INSEE si vous l'avez dans vos données.

Dans ce cas, inutile d'indiquer autre chose que le numéro et le nom de la voie dans les données d'adresse à prendre en compte.
