### ISSUE TITLE
Message Oops, quelque chose tourne pas rond… Si cela persiste, vous pouvez signaler une erreur.

### ISSUE THREAD

**Issue by aubin33160** [etalab/adresse.data.gouv.fr#66]
@jdesboeufs Depuis la derniere mise à jour, La normalisation d'adresse ne fonctionne plus.
Meme pas avec un fichier de test d'une seule adresse
Merci de préciser s'il y a une solution de contournement.
Cordialement

**Comment by ImanCA** [comment]
Bonjour, 
J'ai le même message d'erreur. Etes-vous parvenu à trouver une solution ? 

Merci par avance

**Comment by aurelg** [comment]
Idem ici.

**Comment by brunolavergne** [comment]
Bonjour, j'ai le même problème et je ne sais pas comment modifier le fichier pour le résoudre.
Merci de nous tenir informé.
Cdt.

**Comment by geostonemarten** [comment]
Bonjour, pour répondre j'ai eu le même problème. L'option permettant de choisir le charset (iso-8859-1) ne fait qu'une correction de l'affichage. Je pense qu'il manque en back-office une correction de l'encodage avant d'envoyer les information à l'API d'où le retour d'erreur.

J'ai corrigé mon problème en convertissant le csv en utf-8
Cdt.

**Comment by cquest** [comment]
Si vous rencontrez un problème de géocodage sur un fichier CSV, vous pouvez nous le transmettre par email à adresse@data.gouv.fr

Il est toutefois recommandé :
- d'utiliser l'UTF8
- de ne pas mettre d'accents dans les noms de colonne ou de fichiers

**Comment by brunolavergne** [comment]
Bonjour,
Merci beaucoup pour votre retour.
grâce à vos recommandations, j'arrive à faire passer tous mes fichiers sans problème.
bonne journée.


Le 9 oct. 2017 17:58, Christian Quest <notifications@github.com> a écrit :

Si vous rencontrez un problème de géocodage sur un fichier CSV, vous pouvez nous le transmettre par email à adresse@data.gouv.fr<mailto:adresse@data.gouv.fr>

Il est toutefois recommandé :

  *   d'utiliser l'UTF8
  *   de ne pas mettre d'accents dans les noms de colonne ou de fichiers

**Comment by cquest** [comment]
Plusieurs fichiers "ne passant pas" nous ont été transmis et ne posent en fait aucune problème.

Dans de nombreux cas, le problème semble venir d'une configuration de proxy ou de firewall un peu trop stricte, ne permettant pas d'utiliser l'API en mode batch CSV.

Pensez donc à vérifier ce point avec votre admin réseau... et éventuellement à faire un test depuis un autre accès internet.

**Comment by jdesboeufs** [comment]
Il semble néanmoins y avoir un problème avec l'utilisation du paramètre "postcode" qui est optionnel. Est-il possible de refaire des essais de votre côté sans renseigner ce champ ?

**Comment by brunolavergne** [comment]
OK pas de soucis. je vous fait ça dans la journée pour vous dire ce qu'il en est.

Le 15 oct. 2017 15:06, Jérôme Desboeufs <notifications@github.com> a écrit :

Il semble néanmoins y avoir un problème avec l'utilisation du paramètre "postcode" qui est optionnel. Est-il possible de refaire des essais de votre côté sans renseigner ce champ ?

**Comment by brunolavergne** [comment]
sans renseigner les paramètres optionnels, mes fichiers sont géo-codés sans problèmes (de ce que j'en vois).

je vous les joins si vous voulez vérifier.


________________________________
De : Jérôme Desboeufs <notifications@github.com>
Envoyé : dimanche 15 octobre 2017 15:06
À : etalab/adresse.data.gouv.fr
Cc : brunolavergne; Comment
Objet : Re: [etalab/adresse.data.gouv.fr] Message Oops, quelque chose tourne pas rond… Si cela persiste, vous pouvez signaler une erreur. (#66)


Il semble néanmoins y avoir un problème avec l'utilisation du paramètre "postcode" qui est optionnel. Est-il possible de refaire des essais de votre côté sans renseigner ce champ ?

**Comment by jdesboeufs** [comment]
@aurelg @aubin33160 @ImanCA avez-vous pu faire des essais supplémentaires ?

**Comment by aurelg** [comment]
Pas encore car je n'ai pas eu de nouvelles données à soumettre. Au pire, si vous voulez clore ce bug, ce sera toujours possible de le réouvrir ultérieurement ?

**Comment by jdesboeufs** [comment]
Parfait.
