### ISSUE TITLE
Migration Next.js 4

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/adresse.data.gouv.fr#68]
Pour homogénéiser les sites du pôle géo et préparer les suite, il faut migrer ce site statique vers [Next.js 4](https://zeit.co/blog/next4).

La base de travail de [cadastre.data.gouv.fr](https://github.com/etalab/cadastre.data.gouv.fr) peut être réutilisée.

**Comment by tusbar** [comment]
Closed by #70.
