### ISSUE TITLE
Anomalie adresse : Corniche Fleurie, Nice

### ISSUE THREAD

**Issue by fchabouis** [etalab/adresse.data.gouv.fr#71]
Bonjour,

J'ai été redirigé ici depuis https://github.com/addok/addok/issues/404

Je me rends compte de certaines erreurs en utilisant l'API de adresse.gouv.fr.
Par exemple :

![image](https://user-images.githubusercontent.com/15341118/32171586-ee8a27fe-bd78-11e7-8dd4-daa95749edc8.png)

Le deuxième résultat (avenue de la corniche fleurie) a des coordonnées qui correspondent bien à la route du même nom.
Le premier en revanche nous indique un endroit où aucun route de ce nom n'existe apparement.

Je trouve régulièrement des erreurs de ce type. Ou dois-je les signaler, ou comment puis-je aider à les corriger ?

Merci

**Comment by jdesboeufs** [comment]
@fchabouis Je crains qu'hélas il s'agisse d'erreurs dans le référentiel en lui-même.
Actuellement les mairies (qui sont en charge des adresses) ont à leur disposition un outil permettant d'améliorer les adresses de leur territoire.
Cf https://adresse.data.gouv.fr/contrib

@cquest tu confirmes ?

**Comment by cquest** [comment]
Je n'ai pas trouvé trace d'une "Route de la Corniche Fleurie" dans les données opendata de Nice non plus mais uniquement "Corniche Fleurie" avec 138 numéros et une "Avenue Fleurie" avec 8 numéros.
