### ISSUE TITLE
Fond de plan mixte : orthophoto et cadastre

### ISSUE THREAD

**Issue by I-Thibaud** [etalab/adresse.data.gouv.fr#807]
Mettre à disposition un fond de plan mixte avec la photo aérienne et la couche cadastre sans applats par dessus.

exemple :
![image](https://user-images.githubusercontent.com/84328873/118495727-c4e4cf00-b723-11eb-87af-89b1ccc0c63d.png)

Cela faciliterait grandement la saisie et la fiabilité des données par les communes. Dans notre mode opératoire, nous priorisons la saisie du point adresse dans la parcelle cadastrale et à l'entrée de la propriété. Parfois, le cadastre étant grandement décalé, beaucoup de points se retrouvent hors de la parcelle ou sur une autre parcelle bâtie

Par avance merci,

**Comment by tmerlier** [comment]
Bonjour,

Une nouvelle fonctionnalité permettant l'association d'adresses et de parcelles est en cours de développement. Celle-ci permettra de visualiser le cadastre par dessus le fond vectorielle et aérien déjà proposé.

**Comment by I-Thibaud** [comment]
Bonne nouvelle merci.
