### ISSUE TITLE
Ajouter des liens pour le bulletin d'inscription à l'infolettre et la carte des BAL

### ISSUE THREAD

**Issue by C-Sophie** [etalab/adresse.data.gouv.fr#833]
Aujourd'hui 

- le formulaire d'inscription, situé en bas de page d'accueil https://adresse.data.gouv.fr/
- la carte de déploiement des BAL, située en bas de page des BAL https://adresse.data.gouv.fr/bases-locales 
n'ont pas d'adresse dédiée. On indique aux correspondants de "se rendre sur la page d'accueil et d'aller tout en bas" ou de "se rendre sur la page des Bases Adresses Locales et de se rendre tout en bas"

Avec un lien vers le formulaire d'inscription et un lien vers la carte, il sera plus facile de les réutiliser.

**Comment by tmerlier** [comment]
Le lien vers la carte de déploiement des BAL existe : https://adresse.data.gouv.fr/bases-locales#map-stat. Je me charge de créer un lien vers l'infolettre
