### ISSUE TITLE
Mise à jour page du Guide de Mes Adresses

### ISSUE THREAD

**Issue by C-Sophie** [etalab/adresse.data.gouv.fr#869]
A la suite de la publication de la nouvelle fonctionnalité de certification à l'adresse, le guide PDF a été mis à jour pour être placé en lien ici : https://adresse.data.gouv.fr/guides
[20210906 Guide Mes Adresses 4.1.pdf](https://github.com/etalab/adresse.data.gouv.fr/files/7116602/20210906.Guide.Mes.Adresses.4.1.pdf)

**Comment by rstadel** [comment]
Le guide ne fait pas mention de la possibilité de renseigner la certification d'une adresse via le nouveau champ _certification_adresse_ pour la cas où las base est maintenue en .csv. 
Est-ce que cette information est publiée à un autre endroit ?

**Comment by C-Sophie** [comment]
L'information est disponible ici : https://doc.adresse.data.gouv.fr/mettre-a-jour-sa-base-adresse-locale/publier-une-base-adresse-locale

**Comment by tmerlier** [comment]
Fermée par #871
