### ISSUE TITLE
Adresses certifiées 

### ISSUE THREAD

**Issue by C-Sophie** [etalab/adresse.data.gouv.fr#883]
Ces adresses ont été validées en amont par les communes. 
[Adresses_certifiees.csv](https://github.com/etalab/adresse.data.gouv.fr/files/7175632/Adresses_certifiees.csv)

Le délégataire nous transmet un fichier comprenant le nom de la commune et le code INSEE.

**Comment by jdesboeufs** [comment]
Il convient désormais d'éditer le fichier suivant :
https://github.com/BaseAdresseNationale/ban-plateforme/blob/master/communes-certifiees.csv
