### ISSUE TITLE
[Stats] Pas de comptage des downloads dans Piwik

### ISSUE THREAD

**Issue by ThomasMenant** [etalab/adresse.data.gouv.fr#93]
Juste pour vous dire que nous n'avons pas le nombre de dl sur la page Piwik et c'est dommage.

https://stats.data.gouv.fr/index.php?module=CoreHome&action=index&idSite=13&period=range&date=previous30#?module=Actions&action=menuGetPageUrls&idSite=13&period=range&date=previous30

**Comment by jdesboeufs** [comment]
Les stats sont collectées ailleurs que sur Piwik.

**Comment by odtvince** [comment]
Je crois que c'est bien le problème que signalait @ThomasMenant : les stats étant collectées ailleurs que sur Piwik, elles ne lui sont pas accessibles quand il en a besoin ;-)

**Comment by jdesboeufs** [comment]
OK ;)
Piwik c'est vraiment un sujet ou une page `/stats` peut faire l'affaire ?
